resources:
  - name: myRepo
    type: GitRepo
    configuration:
      path: mjmckay/workshop-jfrog-linkerd
      gitProvider: petclinicRepo
      branches:
        include: main
      buildOn:
        commit:                false
        pullRequestCreate:     false
        releaseCreate:  true

pipelines:
  - name: petclinic_deploy
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: linkerdworkshop.jfrog.io/workshop-docker/alpine/k8slinkerd
            tag: v0.1.0
            autoPull: true
            registry: myArtifactory
            sourceRepository: workshop-docker
    steps:
      - name: kubernetes_deploy
        type: Bash
        configuration:
          integrations:
            - name: myKonfig
          inputResources:
            - name: myRepo
        execution:
          onExecute:
            - cd $res_petclinic_repo_resourcePath/spring-petclinic-cloud
            - export REPOSITORY_PREFIX=springcommunity
            - mkdir $HOME/.kube
            - echo $int_myKonfig_kubeconfig > $HOME/.kube/config
            - cat $HOME/.kube/config
            - kubectl apply -f k8s/init-namespace
            - kubectl apply -f k8s/init-services
            - bash scripts/deployToKubernetes.sh
          onSuccess:
            - echo "Petclinic ${run_number} deployed!"
